CREATE TABLE TBPACIENTES1(
UUID NVARCHAR2(50) PRIMARY KEY,
Nombres NVARCHAR2(100) NOT NULL,
Apellidos NVARCHAR2 (100) NOT NULL,
Edad INT NOT NULL,
Enfermedad NVARCHAR2(100) NOT NULL,
NumHabitacion INT NOT NULL,
NumCama INT NOT NULL,
Medicamentos NVARCHAR2(200) NOT NULL,
FechaIngreso NVARCHAR2(10) NOT NULL,
HoraMedicacion NVARCHAR2(10) NOT NULL
);

Select * from tbPacientes1

